### ISSUE TITLE
Clear cache for given user ID

### ISSUE THREAD

**Issue by MikeElghali** [spatie/laravel-responsecache#106]
Hi,

I would like to clear cache for given user ID. How i can acheive this? Thanks.

Regards.

**Comment by freekmurze** [comment]
This is mentioned in the repo: https://github.com/spatie/laravel-responsecache/blob/54218e9cbeaa1e4753d9546e6c2bec9317d7e757/README.md#creating-a-custom-cache-profile

**Comment by poor-bob** [comment]
I believe this would be a feature request, and one I'd also be very interested in. Anyone willing to provide a PR with passing tests?

Perhaps we can call flush(userId) based on whether a user updates/deletes a resource, rather than when any user updates/deletes a resource (ala flush now),  via the responsecache API

**Comment by poor-bob** [comment]
Ignore me..
