### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by artisaninweb** [spatie/laravel-responsecache#251]
Hi!

Is there a specific reason why PHP 7.3 is required?
We love this package and want to use the newest version.
Because we need the replacers feature.
But our production server is not running PHP 7.3.
Even Laravel 6.0 is not on 7.3 yet.

 If there is, is there an other way to get this package on PHP 7.1/7.2?
Maby by forking it, and changing the composer.json?

Thanks!

**Comment by freekmurze** [comment]
Feel free to fork it.

**Comment by swapnilsarwe** [comment]
@freekmurze - i have created a fork - https://github.com/codeat3/laravel-responsecache-php72 & planning to maintain it along side the original repository. Since i had to use it on one of my productions which has php 7.2.

Do you have any guidelines - which will help me decide - whether i should be keeping tags in sync with the original repository? Is it ok to change all Spatie namespace reference to Codeat3 references?

**Comment by dariusj18** [comment]
Please reconsider the requirement of PHP 7.3, RHEL is still on 7.2

**Comment by damarev** [comment]
I would make an argument about this: since this package is made specifically for laravel, and supports v6, IMHO should have the same php requirements as the laravel/framework v6 repository.

When I do **composer require spatie/laravel-responsecache** I get:
 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.5.0
    - spatie/laravel-responsecache v5.x-dev requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - spatie/laravel-responsecache 5.0.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - spatie/laravel-responsecache 5.0.1 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - spatie/laravel-responsecache 5.0.2 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - spatie/laravel-responsecache 5.0.3 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.5.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.5.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.5.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.5.0].
    - Installation request for laravel/framework (locked at v6.5.0, required as ^6.0) -> satisfiable by laravel/framework[v6.5.0].
    - Installation request for spatie/laravel-responsecache ^5.0 -> satisfiable by spatie/laravel-responsecache[5.0.0, 5.0.1, 5.0.2, 5.0.3, v5.x-dev].
```

In my case scenario (php 7.2.23, laravel 6.5.0), wich specific version should I require? v5.x-dev?
