### ISSUE TITLE
Does this package seem not work on PHP 7.4?

### ISSUE THREAD

**Issue by dungnh** [spatie/laravel-responsecache#264]
I tried to use this package with Laravel 6.5 and PHP 7.4 and I get the error like this:

`syntax error, unexpected 'ResponseCache' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'ResponseCache' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /../vendor/spatie/laravel-responsecache/src/Middlewares/CacheResponse.php:16`

Do you have any idea about this? Thank you.

**Comment by freekmurze** [comment]
Judging by the error message you do not seem to run the expect version of PHP.

**Comment by logan-jobzmall** [comment]
@freekmurze - I am getting the same exact error on 7.3.11 on Amazon Linux. What is the expected version?

**Comment by raymondtri** [comment]
Except I'm getting the same error as well, and I'm running on php 7.4.1 which satisfies what this package's composer.json requires:
`"php": "^7.4",`

**Comment by vesper8** [comment]
getting same exact error on php 7.4

**Comment by vesper8** [comment]
was having same issue just now.. be sure to test which php-fpm is running by using `echo phpinfo();` from inside your laravel app, regardless of what `php -v` says on the command line.

I am using Valet and even though I repeatedly issued `valet use php74` and that command appeared to run correctly, following a restart of the computer my php-fpm was being stuck on php73, as confirmed by phpinfo

that was a load of bs and I had to uninstall all php versions in brew and reinstall using valet and now seems to be working, definitely the error above is caused by not running php74 as your fpm version
