### ISSUE TITLE
Access session data?

### ISSUE THREAD

**Issue by qodeboy** [spatie/laravel-responsecache#27]
Is there any way we can access session data in CacheProfile implementation?

Let's say I have shop website with a currency switcher on it. Selected currency is then stored in a session. Obviously, page cache should depend on selected currency, as prices are changing. 

To do this, I want to override `cacheNameSuffix` method of the `Spatie\ResponseCache\CacheProfilesCacheProfile` interface implementation. In this method, I want to look into session to check selected currency and add it's code to the cache key suffix.

But once I enable response cache, my session turns blank/empty.

Please let me know if you need any other input from me.

**Comment by freekmurze** [comment]
In the testsuite for this package there is [this test](https://github.com/spatie/laravel-responsecache/blob/f4b0230/tests/IntegrationTest.php#L90) that use authenticated user (and thus session data).

So I'm thinking using session data should just work.

Could you submit a failing test?

**Comment by tuimz** [comment]
@freekmurze I have a failing test show that the session is always empty. Not sure if I should submit this in a PR but it is in my fork https://github.com/tuimz/laravel-responsecache

**Comment by freekmurze** [comment]
Go ahead and PR that test

**Comment by freekmurze** [comment]
@tuimz I refactored your test a bit: https://github.com/spatie/laravel-responsecache/blob/81366d0/tests/IntegrationTest.php#L149

On my local machine the test passes.

**Comment by tuimz** [comment]
@freekmurze I have noticed that the session ID is available (which is why the test passes). Although this is the same as not using any cache since the session ID always changes (Atleast for me).

However when you try any other key from the session it will not work as the session is not populated (yet?)

**Comment by freekmurze** [comment]
Yea, I'll remove that test again, it indeed proves nothing.

To fix to problem you could try to make the middleware provided by this package run later.

On the top of my head I have no good idea how to do that.

I've you find a good fix, let me know.

**Comment by freekmurze** [comment]
I think this problem was caused because previous versions of the package pushed the provided middleware to the `middleware` array. These middlewares are started prior to the ones in `web` middleware group where session is started up.

In `v3` of the package the provided middlewares aren't registered automatically anymore. You should install them manually. If you instal the `CacheResponse` middleware as the last item in the `web` group (like the readme suggest) the responsecache should be able to access session data.
