### ISSUE TITLE
Replacer for csrf token

### ISSUE THREAD

**Issue by mgiorgi-github** [spatie/laravel-responsecache#309]
Hi, I've installed your the package, how can use Replacer class into my form?

This is a simple form:

`form method="POST" action="/profile"
    @csrf
    ...
form`

After submit Larevel show expire error and i can't send the message... how can i do?

I've tried to change it like that but i've the same error:

`form method="POST" action="/profile"
    <input type="hidden" name="_token" value="<laravel-responsecache-csrf-token-here>">
    ...
form`

I've a standard configuration like Github installation page.

Thanks

**Comment by haydar** [comment]
I started newly using this package. I am confused like you too. You don't need to do anything for replacing csrf according to my test. I checked to csrf changes after cache enabled on many browsers and I saw csrf is changing...

I think you are newbie about laravel. The way you add csrf token is wrong.

Use the following instead of your code.
`
<form action="{{route('your-route')}}" class="foo-class" method="POST" enctype="multipart/form-data"> @csrf </form>
`
or

`
<form action="{{route('your-route')}}" class="foo-class" method="POST" enctype="multipart/form-data">
<input type="hidden" name="_token" value="{{csrf_token()}}">
</form>
`
