### ISSUE TITLE
error in routing

### ISSUE THREAD

**Issue by AlvaroLopez5** [spatie/laravel-responsecache#58]
The problem is only one page cache and others are wrong! Any idea...
![error](https://cloud.githubusercontent.com/assets/25080138/25683150/24f0bdd6-305b-11e7-81ee-77f8be530639.PNG)

**Comment by freekmurze** [comment]
Things you could try


- verify that you installed the `\Spatie\ResponseCache\Middlewares\CacheResponse::class` like mentioned in the readme
- flushing the cache to see if you have cached the error
- install the package in a vanilla Laravel app to determine if the problem lies with your app or with the package
