### ISSUE TITLE
Add a variable to the output if cached

### ISSUE THREAD

**Issue by Zyles** [spatie/laravel-responsecache#7]
I want to add a variable in the JSON response "fromCache: true" to indicate if the response came from the cache. I don't want to only use the header.

Is there an easy way to do this?

Write to it before it is saved somehow?

**Comment by sebastiandedeyne** [comment]
Hmm I don't think this is currently possible. The responsecache skips as much as the app as possible, and only goes through middleware. If you'd implement it there you'd have to unserialize the json, add the property and reserialize it, which sounds kind of counterproductive.

If it's a json response you could opt to not use this package use Laravel's default cache for the php object, and have more control over it. Since you're not rendering views and your data is all one one place I don't think it would be a huge difference in performance with this package. (Since I don't know your use case this could be completely irrelevant, just throwing some thoughts out)
