### ISSUE TITLE
Can specify for each url cached?

### ISSUE THREAD

**Issue by khanhvu14** [spatie/laravel-responsecache#99]
Thank you so much for your package. It is really useful and necessary.
But I have a question? Can I delete specify cache for each url?

**Comment by vjolenz** [comment]
This package has no support for your use case but I can recommend you a workaround . Since this packages creates a md5 hash from request as cache key, if you create the same hash(cache key) you should be able to delete cache by this hash.

Check out this link for hashing method -> https://github.com/spatie/laravel-responsecache/blob/ee30b9dab79b13f77605360f58e69d2ebdb0bfaa/src/RequestHasher.php#L18

**Comment by khanhvu14** [comment]
Thank you for u guide. I know what I need to do.
